esphome:
  name: d0-pulse-meter
  friendly_name: "Energy meter"

esp8266:
  board: d1_mini

logger:

api:
  reboot_timeout: 0s
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: !secret ap_wifi_ssid
    password: !secret ap_wifi_password

captive_portal:

web_server:

sensor:
  - platform: pulse_meter
    name: "Instantaneous Power"
    pin: GPIO5
    unit_of_measurement: 'W'
    accuracy_decimals: 0
    internal_filter_mode: EDGE
    internal_filter: 60ms
    filters:
      - multiply: 30
