# See https://github.com/syssi/esphome-smg-ii/issues/19

globals:
  - id: total_pulses
    type: int
    restore_value: true
    initial_value: '7470502'

esphome:
  name: gas-meter
  friendly_name: "Gas meter"
  min_version: 2024.6.0

esp8266:
  board: d1_mini
  restore_from_flash: true

preferences:
  flash_write_interval: 10min

logger:

api:
  reboot_timeout: 0s
  encryption:
    key: !secret api_encryption_key

ota:
  platform: esphome
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: !secret ap_wifi_ssid
    password: !secret ap_wifi_password

captive_portal:

web_server:

button:
  - platform: template
    name: "Reset total pulses"
    on_press:
      - lambda: id(total_pulses) = 0;

binary_sensor:
  - platform: gpio
    id: reed
    pin:
      number: GPIO5
      mode: INPUT_PULLUP
    name: "Reed contact closed"
    filters:
      - delayed_on: 20ms
    on_press:
      then:
        - lambda: id(total_pulses) += 1;
        - output.turn_off: led
    on_release:
      then:
        - output.turn_on: led

sensor:
  - platform: template
    name: "Meter Reading"
    device_class: gas
    unit_of_measurement: "m³"
    state_class: "total_increasing"
    icon: "mdi:fire"
    accuracy_decimals: 2
    update_interval: 60s
    lambda: |-
      return id(total_pulses) * 0.01f;

output:
  - platform: gpio
    pin: GPIO2
    id: led
